### ISSUE TITLE
ImportError: libgnuradio-acars2.so

### ISSUE THREAD

**Issue by f4hbw** [antoinet/gr-acars2#3]
Hello, 

I'm trying to use your program. I managed to install it without any problem. 

But when I try to launch it in GRC 3.7 i get this error message : 

Traceback (most recent call last):
  File "/home/kevin/RecepteurFM.py", line 19, in <module>
    import acars2
  File "/usr/local/lib/python2.7/dist-packages/acars2/**init**.py", line 45, in <module>
    from acars2_swig import *
  File "/usr/local/lib/python2.7/dist-packages/acars2/acars2_swig.py", line 28, in <module>
    _acars2_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/acars2/acars2_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_acars2_swig', fp, pathname, description)
ImportError: libgnuradio-acars2.so: cannot open shared object file: No such file or directory

Thanks in advance, best regards. 

F4HBW, Kévin.

**Comment by lepido** [comment]
Is there a solution to this problem? I am having a similiar problem on Mac OS 10.10 with GRC 3.7.8 (via MacPorts).

All files are in the right place but it doesn't find the acars2.dylib which is referenced by the .so file.

**Comment by lepido** [comment]
In case you are on a Mac, this might be the problem (and solve it):
https://software.intel.com/en-us/articles/linking-and-redistributing-intel-dynamic-libaries-on-mac-os-x

Or you recompile the module with a modified CMakeList.txt:
https://gnuradio.org/redmine/projects/gnuradio/wiki/MacInstall#Library-not-found
